CREATE TABLE "PRODUTO"(
    "ID_PRODUTO" INTEGER PRIMARY KEY,
    "DESC_PRODUTO" VARCHAR2(100),
    "VALOR_PRODUTO" NUMBER
);

-- Inserindo dados na tabela "PRODUTO"
INSERT INTO "PRODUTO" ("ID_PRODUTO", "DESC_PRODUTO", "VALOR_PRODUTO") VALUES (1, 'Produto A', 10.99);
INSERT INTO "PRODUTO" ("ID_PRODUTO", "DESC_PRODUTO", "VALOR_PRODUTO") VALUES (2, 'Produto B', 25.49);
INSERT INTO "PRODUTO" ("ID_PRODUTO", "DESC_PRODUTO", "VALOR_PRODUTO") VALUES (3, 'Produto C', 5.75);
INSERT INTO "PRODUTO" ("ID_PRODUTO", "DESC_PRODUTO", "VALOR_PRODUTO") VALUES (4, 'Produto D', 15.99);
INSERT INTO "PRODUTO" ("ID_PRODUTO", "DESC_PRODUTO", "VALOR_PRODUTO") VALUES (5, 'Produto E', 8.25);
INSERT INTO "PRODUTO" ("ID_PRODUTO", "DESC_PRODUTO", "VALOR_PRODUTO") VALUES (6, 'Produto F', 19.99);
INSERT INTO "PRODUTO" ("ID_PRODUTO", "DESC_PRODUTO", "VALOR_PRODUTO") VALUES (7, 'Produto G', 12.50);
INSERT INTO "PRODUTO" ("ID_PRODUTO", "DESC_PRODUTO", "VALOR_PRODUTO") VALUES (8, 'Produto H', 7.75);
INSERT INTO "PRODUTO" ("ID_PRODUTO", "DESC_PRODUTO", "VALOR_PRODUTO") VALUES (9, 'Produto I', 14.99);
INSERT INTO "PRODUTO" ("ID_PRODUTO", "DESC_PRODUTO", "VALOR_PRODUTO") VALUES (10, 'Produto J', 9.99);
INSERT INTO "PRODUTO" ("ID_PRODUTO", "DESC_PRODUTO", "VALOR_PRODUTO") VALUES (11, 'Produto K', 12.25);
INSERT INTO "PRODUTO" ("ID_PRODUTO", "DESC_PRODUTO", "VALOR_PRODUTO") VALUES (12, 'Produto L', 6.50);
INSERT INTO "PRODUTO" ("ID_PRODUTO", "DESC_PRODUTO", "VALOR_PRODUTO") VALUES (13, 'Produto M', 17.75);
INSERT INTO "PRODUTO" ("ID_PRODUTO", "DESC_PRODUTO", "VALOR_PRODUTO") VALUES (14, 'Produto N', 22.99);
INSERT INTO "PRODUTO" ("ID_PRODUTO", "DESC_PRODUTO", "VALOR_PRODUTO") VALUES (15, 'Produto O', 14.50);
INSERT INTO "PRODUTO" ("ID_PRODUTO", "DESC_PRODUTO", "VALOR_PRODUTO") VALUES (16, 'Produto P', 8.75);
INSERT INTO "PRODUTO" ("ID_PRODUTO", "DESC_PRODUTO", "VALOR_PRODUTO") VALUES (17, 'Produto Q', 11.99);
INSERT INTO "PRODUTO" ("ID_PRODUTO", "DESC_PRODUTO", "VALOR_PRODUTO") VALUES (18, 'Produto R', 19.25);
INSERT INTO "PRODUTO" ("ID_PRODUTO", "DESC_PRODUTO", "VALOR_PRODUTO") VALUES (19, 'Produto S', 5.99);
INSERT INTO "PRODUTO" ("ID_PRODUTO", "DESC_PRODUTO", "VALOR_PRODUTO") VALUES (20, 'Produto T', 10.00);

SELECT * FROM "PRODUTO";

SELECT * FROM "PRODUTO" WHERE ID_PRODUTO = 1;
SELECT * FROM "PRODUTO" WHERE ID_PRODUTO > 1;
SELECT * FROM "PRODUTO" WHERE ID_PRODUTO < 2;
SELECT * FROM "PRODUTO" WHERE ID_PRODUTO <= 2;
SELECT * FROM "PRODUTO" WHERE ID_PRODUTO >= 2;
SELECT * FROM "PRODUTO" WHERE ID_PRODUTO <> 2;

SELECT * FROM "PRODUTO" WHERE ID_PRODUTO >= 2 AND ID_PRODUTO <=5;

SELECT * FROM "PRODUTO" WHERE DESC_PRODUTO='Produto A' or DESC_PRODUTO='Produto Z';

SELECT * FROM "PRODUTO" WHERE ID_PRODUTO BETWEEN 1 AND 5;

SELECT * FROM "PRODUTO" WHERE DESC_PRODUTO IN('Produto A', 'Produto B', 'Produto Z');

SELECT 
    VALOR_PRODUTO AS VP,
    ROUND(VALOR_PRODUTO,1) AS VP_ARR,
    TRUNC(VALOR_PRODUTO,1) AS VP_TRUNC,
    MOD(VALOR_PRODUTO,2) AS VP_MOD,
    SQRT(VALOR_PRODUTO) RAIZ_QUADRADA,
    CEIL(VALOR_PRODUTO), 
    FLOOR(VALOR_PRODUTO)
FROM PRODUTO;

SELECT
    LOWER (DESC_PRODUTO),
    UPPER(DESC_PRODUTO),
    INITCAP(DESC_PRODUTO)
FROM PRODUTO;


SELECT
    CONCAT('EM OFERTA ', DESC_PRODUTO),
    LENGTH(DESC_PRODUTO),
    REPLACE(DESC_PRODUTO, 'r', 'X')
FROM PRODUTO;
