DROP TABLE ALUNO;
DROP TABLE ENDERECO;

CREATE TABLE ESTUDANTE (
    RA INTEGER PRIMARY KEY,
    NOME VARCHAR(60),
    cep INTEGER,
    cpf VARCHAR(15),
    FOREIGN KEY (cep) REFERENCES ENDERECO(cep)
);

CREATE TABLE ENDERECO (
    cep integer primary key,
    rua varchar(60),
    cidade varchar(60)
);  

-- ADICIONOU UMA COLUNA
ALTER TABLE ESTUDANTE
    ADD CPF VARCHAR(15) NOT NULL;

ALTER TABLE ALUNO
    ADD CEP INTEGER;
    
-- ADICIONANDO UMA CHAVE PRIMÁRIA
ALTER TABLE ALUNO
    ADD CONSTRAINT PK_ALUNO1 PRIMARY KEY(RA);
    
-- ADICIONANDO UMA CHAVE ESTRANGEIRA 
ALTER TABLE ESTUDANTE
    ADD CONSTRAINT FK_ALUNO_ENDERECO 
    FOREIGN KEY (CEP) REFERENCES ENDERECO(CEP);
    
-- DESC: DESCRIBE (DEMONSTRAR A ARQUITETURA DA TABELA)   

-- REMOVER UMA COLUNA
ALTER TABLE ALUNO
    DROP COLUMN CPF;

-- MODIFICANDO UMA COLUNA
ALTER TABLE ALUNO
    MODIFY NOME CHAR(20);
    
-- RENOMEANDO UMA COLUNA
ALTER TABLE ESTUDANTE
    RENAME COLUMN NOME TO NOME_COMPLETO;
    
-- RENOMEANDO UMA TABELA    
RENAME ALUNO TO ESTUDANTE;

--DESC ALUNO;   
DESC ESTUDANTE;

DROP TABLE ENDERECO CASCADE CONSTRAINTS;


INSERT INTO ESTUDANTE (RA,NOME_COMPLETO, CPF)
    VALUES (1,'DIOGO', '2222222');
    
INSERT INTO ESTUDANTE (RA,NOME_COMPLETO, CPF)
    VALUES (2,'MARCELO', '3333333');
    
INSERT INTO ESTUDANTE (RA,NOME_COMPLETO, CPF)
    VALUES (3,'KAIQUE', '44444444');

TRUNCATE TABLE ESTUDANTE; 

INSERT INTO ESTUDANTE VALUES (2,'MARIA', 00000);    
SELECT * FROM ESTUDANTE;

UPDATE ESTUDANTE SET NOME_COMPLETO='LARISSA';

UPDATE ESTUDANTE SET NOME_COMPLETO='KAIQUE' WHERE RA=1;

UPDATE ESTUDANTE SET NOME_COMPLETO='KAIQUE' WHERE RA>=1;